name: Up-Merge Workflow

on:
  push:
    branches:
      - 'stage'

jobs:
  up-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Up-Merge 'stage' into 'main
        uses: ridedott/up-merge@v3
        with:
          github_token: ${{ secrets.UP_MERGE_PAT }}
          source_branch: 'stage'
          target_branch: 'main'
