name: Up-Merge Workflow

on:
  push:
    branches:
      - 'stage'

jobs:
  up-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Up-Merge 'stage' into 'main'
        uses: bambamboole/gha-upmerge@master
        with:
          base_branch: 'main'
          head_branch: 'stage'
          token: ${{ secrets.UP_MERGE_PAT }}
